[package]
name = "rifling"
version = "0.1.0"
authors = ["Kay Lin <kaymw@aosc.io>"]
edition = "2018"

[dependencies]
hex = "0.3"
log = "0.4"
url = "1.7"
ring = "0.14"
hyper = "0.12"
futures = "0.1"

[dev-dependencies]
pretty_env_logger = "0.3"