[package]
name = "rifling"
description = "A library for creating Github webhook listener"
version = "0.1.1"
authors = ["Kay Lin <kaymw@aosc.io>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["github", "webhook", "ci"]
homepage = "https://github.com/RedL0tus/rifling"
repository = "https://github.com/RedL0tus/rifling"

[badges]
maintenance = { status = "experimental" }

[dependencies]
hex = "0.3"
log = "0.4"
url = "1.7"
ring = "0.14"
hyper = "0.12"
futures = "0.1"

[dev-dependencies]
pretty_env_logger = "0.3"