[package]
name = "rifling"
description = "A library for creating Github webhook listener"
version = "0.2.1"
authors = ["Kay Lin <i@v2bv.net>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["github", "webhook", "ci"]
homepage = "https://github.com/RedL0tus/rifling"
repository = "https://github.com/RedL0tus/rifling"

[badges]
maintenance = { status = "experimental" }

[features]
default = ["hyper-support", "parse"]
hyper-support = ["hyper", "futures"]
parse = ["serde_json"]

[dependencies]
hex = "0.3"
log = "0.4"
url = "1.7"
ring = "0.14"
hyper = { version = "0.12", optional = true }
futures = { version = "0.1", optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
pretty_env_logger = "0.3"